Remove the Kanban board workflow
pulp/plugin_template pull request #900
Opened 2024-07-24 14:59 UTC by lubosmj

[noissue]

2024-07-24 16:47 UTC, ggainey requested changes
Do we want to check for kanban.yml as a "deprecated file"?

2024-07-24 17:10 UTC, lubosmj commented
Not a bad idea.

2024-07-24 18:29 UTC, ggainey approved these changes
Good deal - thanks!

2024-07-25 06:42 UTC, mdellweg approved these changes

2024-07-25 06:42 UTC, merged